//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGumboBackfill
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgnitionEnterpriseReportingEntities : DbContext
    {
        public IgnitionEnterpriseReportingEntities()
            : base("name=IgnitionEnterpriseReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sqlth_drv> sqlth_drv { get; set; }
        public virtual DbSet<sqlth_sce> sqlth_sce { get; set; }
        public virtual DbSet<sqlth_scinfo> sqlth_scinfo { get; set; }
        public virtual DbSet<sqlth_te> sqlth_te { get; set; }
        public virtual DbSet<sqlth_1_data> sqlth_1_data { get; set; }
        public virtual DbSet<sqlth_1_data_20191016> sqlth_1_data_20191016 { get; set; }
    }
}
