//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGumboBackfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlth_drv
    {
        public int id { get; set; }
        public string name { get; set; }
        public string provider { get; set; }
        public string nice_name { get; set; }
        public string division { get; set; }
        public string active { get; set; }
        public string control_system { get; set; }
        public string EGN { get; set; }
        public string rig_status { get; set; }
        public Nullable<System.DateTime> hist_prov_date { get; set; }
        public Nullable<System.DateTime> edge_prov_date { get; set; }
        public Nullable<System.DateTime> ace_os_prov_date { get; set; }
    }
}
