//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGumboBackfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlth_scinfo
    {
        public int id { get; set; }
        public string scname { get; set; }
        public Nullable<int> drvid { get; set; }
    }
}
