//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGumboBackfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlth_1_data
    {
        public int tagid { get; set; }
        public Nullable<long> intvalue { get; set; }
        public Nullable<double> floatvalue { get; set; }
        public string stringvalue { get; set; }
        public Nullable<System.DateTime> datevalue { get; set; }
        public Nullable<int> dataintegrity { get; set; }
        public long t_stamp { get; set; }
    }
}
