//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGumboBackfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlth_sce
    {
        public int scid { get; set; }
        public long start_time { get; set; }
        public long end_time { get; set; }
        public int rate { get; set; }
    }
}
