//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGumboBackfill
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlth_te
    {
        public int id { get; set; }
        public string tagpath { get; set; }
        public Nullable<int> scid { get; set; }
        public Nullable<int> datatype { get; set; }
        public Nullable<int> querymode { get; set; }
        public Nullable<long> created { get; set; }
        public Nullable<long> retired { get; set; }
    }
}
