//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Alias
    {
        public int BA_AliasID { get; set; }
        public bool ActiveInd { get; set; }
        public int BusinessAssociate_BusinessAssociateID { get; set; }
        public int Alias_BusinessAssociateID { get; set; }
        public Nullable<int> AliasType_rAliasTypeID { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> RowChangedDate { get; set; }
        public Nullable<System.DateTime> RowCreatedDate { get; set; }
        public string password { get; set; }
    }
}
