//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalTagPathSelector
    {
        public string tag { get; set; }
        public string control_system { get; set; }
        public int attempt_ordinal { get; set; }
        public string rig { get; set; }
        public string tag_path { get; set; }
        public string remarks { get; set; }
        public bool is_inverse { get; set; }
        public double uom_factor { get; set; }
        public double uom_intercept { get; set; }
        public string uom_which_applies_first { get; set; }
        public Nullable<System.Guid> unique_id { get; set; }
    }
}
