//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellUOMForEDR
    {
        public int WellUOMForEDRID { get; set; }
        public int Well_WellID { get; set; }
        public bool ActiveInd { get; set; }
        public string BitDepth { get; set; }
        public string HoleDepth { get; set; }
        public string HookLoad { get; set; }
        public string StandpipePressure { get; set; }
        public string Pump1StrokeRate { get; set; }
        public string Pump2StrokeRate { get; set; }
        public string RotaryRPM { get; set; }
        public string RotaryTorque { get; set; }
        public string WeightOnBit { get; set; }
        public string OnBottomROP { get; set; }
        public string Flow { get; set; }
        public string TotalMudVolume { get; set; }
        public string Megajoules { get; set; }
        public string MudDensity { get; set; }
        public string MudViscosity { get; set; }
        public string TotalPumpOutput { get; set; }
        public string OnBottomHours { get; set; }
        public string CirculatingHours { get; set; }
        public string ToolFace { get; set; }
        public string Inclination { get; set; }
        public string Azimuth { get; set; }
        public string Gamma { get; set; }
        public string OverPull { get; set; }
        public string MudGainLoss { get; set; }
        public string DifferentialPressure { get; set; }
        public string PasonGas { get; set; }
        public string TripSpeed { get; set; }
        public string GammaDepth { get; set; }
        public string ThirdPartyGas { get; set; }
        public string FluidLoss { get; set; }
        public string MudPH { get; set; }
        public string PlasticViscosity { get; set; }
        public string YieldPoint { get; set; }
        public string TimeOfPenetration { get; set; }
        public string BlockHeight { get; set; }
        public Nullable<System.DateTime> RowChangedDate { get; set; }
        public Nullable<System.DateTime> RowCreatedDate { get; set; }
        public string SurveyDepth { get; set; }
        public string MagneticToolface { get; set; }
        public string InSlips { get; set; }
    
        public virtual Well Well { get; set; }
    }
}
