//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellTrippingSpeed
    {
        public int WellTrippingSpeedID { get; set; }
        public int Well_WellID { get; set; }
        public string RigNumber { get; set; }
        public string ActivityDescription { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public Nullable<System.DateTime> ToDateTime { get; set; }
        public Nullable<double> ActiveTime { get; set; }
        public string DrillerNames { get; set; }
        public string Remark { get; set; }
        public Nullable<double> DataQualityVote { get; set; }
        public string Warnings { get; set; }
        public string IsBitInCasing { get; set; }
        public string IsCrewHandlingBHA { get; set; }
        public string RemarkCodes { get; set; }
        public Nullable<double> Missing { get; set; }
        public System.DateTime RowCreatedDate { get; set; }
        public Nullable<double> ActiveDeltaBlockHeight { get; set; }
        public Nullable<double> ActiveDeltaBitDepth { get; set; }
        public Nullable<double> FromBitDepth { get; set; }
        public Nullable<double> ToBitDepth { get; set; }
        public Nullable<double> ActiveDistanceTravelled { get; set; }
        public string SinglesOrStands { get; set; }
        public Nullable<double> AvgStoSConnectTime { get; set; }
        public Nullable<int> NumberOfConnections { get; set; }
    
        public virtual Well Well { get; set; }
    }
}
