//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellDrillBitPeriod
    {
        public int WellDrillBitPeriodID { get; set; }
        public Nullable<bool> ActiveInd { get; set; }
        public string Source { get; set; }
        public Nullable<int> Tour_WellDrillPeriodID { get; set; }
        public Nullable<int> BitIntervalObsNo { get; set; }
        public Nullable<decimal> AvgForceOnBit { get; set; }
        public string AvgForceOnBitUOM { get; set; }
        public Nullable<decimal> AvgRotaryRPM { get; set; }
        public Nullable<decimal> BaseDepth { get; set; }
        public string BaseDepthUOM { get; set; }
        public Nullable<decimal> TopDepth { get; set; }
        public string TopDepthUOM { get; set; }
        public Nullable<int> DrillOpType_rWellDrillOpTypeID { get; set; }
        public Nullable<decimal> Torque { get; set; }
        public string TorqueUOM { get; set; }
        public Nullable<System.DateTime> RowChangedDate { get; set; }
        public Nullable<System.DateTime> RowCreatedDate { get; set; }
        public string DepthDrilledFormation_Ensign { get; set; }
    
        public virtual WellDrillPeriod WellDrillPeriod { get; set; }
    }
}
