//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellEDR
    {
        public int WellEdrID { get; set; }
        public Nullable<int> Well_WellID { get; set; }
        public Nullable<System.DateTime> MeasurementDate { get; set; }
        public Nullable<System.TimeSpan> MeasurementTime { get; set; }
        public Nullable<System.DateTimeOffset> MeasurementDateTime { get; set; }
        public Nullable<decimal> BitDepth { get; set; }
        public Nullable<decimal> HoleDepth { get; set; }
        public Nullable<decimal> HookLoad { get; set; }
        public Nullable<decimal> StandpipePressure { get; set; }
        public Nullable<int> Pump1StrokeRate { get; set; }
        public Nullable<int> Pump2StrokeRate { get; set; }
        public Nullable<decimal> RotaryRPM { get; set; }
        public Nullable<decimal> RotaryTorque { get; set; }
        public Nullable<decimal> WeightOnBit { get; set; }
        public Nullable<decimal> OnBottomROP { get; set; }
        public Nullable<decimal> Flow { get; set; }
        public Nullable<decimal> TotalMudVolume { get; set; }
        public Nullable<decimal> Megajoules { get; set; }
        public Nullable<decimal> MudDensity { get; set; }
        public Nullable<decimal> MudViscosity { get; set; }
        public Nullable<decimal> TotalPumpOutput { get; set; }
        public Nullable<decimal> OnBottomHours { get; set; }
        public Nullable<decimal> CirculatingHours { get; set; }
        public Nullable<decimal> ToolFace { get; set; }
        public Nullable<decimal> Inclination { get; set; }
        public Nullable<decimal> Azimuth { get; set; }
        public Nullable<decimal> Gamma { get; set; }
        public Nullable<decimal> OverPull { get; set; }
        public Nullable<decimal> MudGainLoss { get; set; }
        public Nullable<decimal> DifferentialPressure { get; set; }
        public Nullable<decimal> PasonGas { get; set; }
        public Nullable<decimal> TripSpeed { get; set; }
        public Nullable<decimal> GammaDepth { get; set; }
        public Nullable<decimal> ThirdPartyGas { get; set; }
        public Nullable<decimal> FluidLoss { get; set; }
        public Nullable<decimal> MudPH { get; set; }
        public Nullable<decimal> PlasticViscosity { get; set; }
        public Nullable<decimal> YieldPoint { get; set; }
        public Nullable<decimal> TimeOfPenetration { get; set; }
        public Nullable<decimal> BlockHeight { get; set; }
        public string RigState { get; set; }
        public string RigStateOverride { get; set; }
        public Nullable<decimal> OriginalBitDepth { get; set; }
        public Nullable<decimal> OriginalHoleDepth { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> OperatingDay { get; set; }
        public Nullable<decimal> SurveyDepth { get; set; }
        public Nullable<decimal> MagneticToolface { get; set; }
        public Nullable<double> SpudToTD_day { get; set; }
        public Nullable<bool> InSlips { get; set; }
        public Nullable<decimal> OriginalOnBottomROP { get; set; }
    
        public virtual Well Well { get; set; }
    }
}
