//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Well()
        {
            this.WellConnectTimes = new HashSet<WellConnectTime>();
            this.WellDrillPeriods = new HashSet<WellDrillPeriod>();
            this.WellTrippingSpeeds = new HashSet<WellTrippingSpeed>();
            this.WellEDRs = new HashSet<WellEDR>();
            this.WellUOMForEDRs = new HashSet<WellUOMForEDR>();
        }
    
        public int WellID { get; set; }
        public string UWI { get; set; }
        public bool ActiveInd { get; set; }
        public string WellName { get; set; }
        public string JobNum { get; set; }
        public string PPDMGuid { get; set; }
        public string WellNum { get; set; }
        public Nullable<System.DateTimeOffset> SpudDate { get; set; }
        public Nullable<System.DateTimeOffset> RigReleaseDate { get; set; }
        public Nullable<int> ProvinceState_rProvinceStateID { get; set; }
        public Nullable<decimal> KBElev { get; set; }
        public string KBElevUOM { get; set; }
        public Nullable<int> LegalSurveyType_rLegalSurveyTypeID { get; set; }
        public Nullable<int> Operator_BusinessAssociateID { get; set; }
        public string PrimarySource { get; set; }
        public Nullable<int> ProfileType_rWellProfileTypeID { get; set; }
        public bool DrillingDataDownloaded { get; set; }
        public Nullable<decimal> DrillTD { get; set; }
        public string DrillTDUom { get; set; }
        public bool WasLegacy22Data { get; set; }
        public Nullable<System.DateTime> RowChangedDate { get; set; }
        public Nullable<System.DateTime> RowCreatedDate { get; set; }
        public string LeaseName { get; set; }
        public string County { get; set; }
        public Nullable<decimal> WaterDepth { get; set; }
        public string WaterDepthUOM { get; set; }
        public Nullable<int> AssignedField_FieldID { get; set; }
        public Nullable<int> CurrentClass_rWellClassID { get; set; }
        public Nullable<decimal> GroundElev { get; set; }
        public Nullable<int> WellStatus_rWellStatusId { get; set; }
        public bool TightHole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellConnectTime> WellConnectTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDrillPeriod> WellDrillPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellTrippingSpeed> WellTrippingSpeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellEDR> WellEDRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellUOMForEDR> WellUOMForEDRs { get; set; }
    }
}
