//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellDrillPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WellDrillPeriod()
        {
            this.WellDrillBitPeriods = new HashSet<WellDrillBitPeriod>();
            this.WellDrillPeriodRemarks = new HashSet<WellDrillPeriodRemark>();
        }
    
        public int WellDrillPeriodID { get; set; }
        public int Well_WellID { get; set; }
        public System.DateTimeOffset StartDateTime { get; set; }
        public int PeriodObsNo { get; set; }
        public bool ActiveInd { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> BoilerFuel { get; set; }
        public string BoilerFuelUOM { get; set; }
        public Nullable<int> Contractor_BusinessAssociateID { get; set; }
        public string ContractorRepName { get; set; }
        public Nullable<bool> ContractorRepSignedInd { get; set; }
        public Nullable<int> CumRigSafetyDays { get; set; }
        public Nullable<int> CumCrewSafetyDays { get; set; }
        public Nullable<System.DateTimeOffset> EndDateTime { get; set; }
        public Nullable<int> AFE_FinanceID { get; set; }
        public Nullable<decimal> HoleDragUp { get; set; }
        public Nullable<decimal> HoleDragDown { get; set; }
        public string HoleDragUOM { get; set; }
        public Nullable<decimal> HoleFillLength { get; set; }
        public string HoleFillLengthUOM { get; set; }
        public Nullable<int> MudSystemType_rDrillingMediaID { get; set; }
        public Nullable<bool> MudTypeOilInd { get; set; }
        public Nullable<bool> MudTypeWaterInd { get; set; }
        public Nullable<int> Operator_BusinessAssociateID { get; set; }
        public Nullable<decimal> OperatorFuel { get; set; }
        public string OperatorFuelUOM { get; set; }
        public string OperatorRepName { get; set; }
        public Nullable<bool> OperatorRepSignedInd { get; set; }
        public Nullable<bool> ReentryInd { get; set; }
        public string ReportedRigName { get; set; }
        public Nullable<int> ReportTimeType_rReportTimeTypeID { get; set; }
        public Nullable<decimal> RigFuel { get; set; }
        public string RigFuelUOM { get; set; }
        public string SafetyMeetingTopic { get; set; }
        public Nullable<decimal> BHAWeight { get; set; }
        public string BHAWeightUOM { get; set; }
        public Nullable<int> DrillPipeSingleCount { get; set; }
        public Nullable<decimal> DrillPipeSingleLen { get; set; }
        public string DrillPipeSingleLenUOM { get; set; }
        public Nullable<int> DrillPipeStandCount { get; set; }
        public Nullable<decimal> DrillPipeStandLen { get; set; }
        public string DrillPipeStandLenUOM { get; set; }
        public Nullable<decimal> KBDownLength { get; set; }
        public string KBDownLengthUOM { get; set; }
        public Nullable<decimal> TotDrillToolWeight { get; set; }
        public string TotDrillToolWeightUOM { get; set; }
        public Nullable<decimal> CircPressure { get; set; }
        public string CircPressureUOM { get; set; }
        public Nullable<int> CircPressureType_rWellCircPressTypeID { get; set; }
        public Nullable<int> CampInd { get; set; }
        public Nullable<decimal> HookloadMax { get; set; }
        public string HookloadMaxUOM { get; set; }
        public string DrillerSignature { get; set; }
        public Nullable<decimal> CasingPressMax { get; set; }
        public string CasingPressMaxUOM { get; set; }
        public Nullable<bool> CaodcMudAllowance { get; set; }
        public Nullable<System.DateTime> RowChangedDate { get; set; }
        public Nullable<System.DateTime> RowCreatedDate { get; set; }
        public Nullable<decimal> TotDrillToolLength { get; set; }
        public string TotDrillToolLengthUOM { get; set; }
    
        public virtual Well Well { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDrillBitPeriod> WellDrillBitPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WellDrillPeriodRemark> WellDrillPeriodRemarks { get; set; }
    }
}
